### ISSUE TITLE
Can't run City_car test script

### ISSUE THREAD

**Issue by tsbiosky** [azadis/CompositionalGAN#6]
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f102ecc1940>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8775): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f102ecc1940>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/usr/local/lib/python3.6/dist-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8775): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f102ecc1940>: Failed to establish a new connection: [Errno 111] Connection refused',))
[Errno 101] Network is unreachable
[Errno 101] Network is unreachable
[Errno 101] Network is unreachable
Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout.
Test Model
/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of cuda is deprecated:
        cuda(torch.device device, bool async, *, torch.memory_format memory_format)
Consider using one of the following signatures instead:
        cuda(torch.device device, bool non_blocking, *, torch.memory_format memory_format)
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3289: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3226: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "test_composition.py", line 53, in <module>
    model.forward_test()
  File "/mnt/oss/luci-hangzhou/junxuan/notebooks/CompositionalGAN/models/objCompose_unsupervised_model.py", line 323, in forward_test
    self.mask_A1_T = (self.mask_A1_T<self.opt.Thresh1*torch.max(self.mask_A1_T).data[0]).type(torch.cuda.FloatTensor)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by azadis** [comment]
Issues should be resolved now in #7 . Also, make sure you start the visdom server in a separate screen:
```python -m visdom.server -p 8775```

**Comment by WorldMeng** [comment]
> ## 用户代码中的异常：
> 回溯（最后一次调用）： 文件“/usr/lib/python3/dist-packages/urllib3/connection.py”，第 141 行，在 _new_conn (self.host, self.port), self.timeout, **extra_kw ） 文件“/usr/lib/python3/dist-packages/urllib3/util/connection.py”，第83行，在create_connection 引发错误 文件“/usr/lib/python3/dist-packages/urllib3/util/connection.py "，第 73 行，在 create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection denied
> 
> 在处理上述异常的过程中，又出现了一个异常：
> 
> 回溯（最后一次调用）： 文件“/usr/lib/python3/dist-packages/urllib3/connectionpool.py”，第 601 行，在 urlopen chunked=chunked） 文件“/usr/lib/python3/dist-packages/ urllib3/connectionpool.py”，第 357 行，在 _make_request conn.request(method, url, **httplib_request_kw) 文件“/usr/lib/python3.6/http/client.py”，第 1264 行，在请求 self._send_request （方法、url、正文、标头、encode_chunked） 文件“/usr/lib/python3.6/http/client.py”，第 1310 行，在 _send_request self.endheaders（body，encode_chunked=encode_chunked） 文件“/usr/lib /python3.6/http/client.py"，第 1259 行，在 endheaders 中 self._send_output(message_body, encode_chunked=encode_chunked) 文件“/usr/lib/python3.6/http/client.py”，第 1038 行，在 _send_output self.send(msg) 文件“/usr/lib/python3.6/http/client.py”，第 976 行，在发送 self.connect() 文件“/usr/lib/python3/dist-packages/urllib3/connection.py”，第 166 行，在连接 conn = self._new_conn() 文件“/usr/lib/python3/dist- packages/urllib3/connection.py”，第 150 行，在 _new_conn self 中，“无法建立新连接：%s”% e) urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f102ecc1940>: 无法建立新连接：[Errno 111] 连接被拒绝
> 
> 在处理上述异常的过程中，又出现了一个异常：
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send timeout=timeout File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen _stacktrace=sys.exc_info()[2]) File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8775): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f102ecc1940>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/visdom/**init**.py", line 711, in _send data=json.dumps(msg), File "/usr/local/lib/python3.6/dist-packages/visdom/**init**.py", line 677, in _handle_post r = self.session.post(url, data=data) File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 578, in post return self.request('POST', url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8775): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f102ecc1940>: Failed to establish a new connection: [Errno 111] Connection refused',)) [Errno 101] Network is unreachable [Errno 101] Network is unreachable [Errno 101] Network is unreachable Visdom python client failed to establish socket to get messages from the server. This feature is optional and can be disabled by initializing Visdom with `use_incoming_socket=False`, which will prevent waiting for this request to timeout. Test Model /pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of cuda is deprecated: cuda(torch.device device, bool async, *, torch.memory_format memory_format) Consider using one of the following signatures instead: cuda(torch.device device, bool non_blocking, _, torch.memory_format memory_format) /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3289: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details. warnings.warn("Default grid_sample and affine_grid behavior has changed " /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:3226: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details. warnings.warn("Default grid_sample and affine_grid behavior has changed " Traceback (most recent call last): File "test_composition.py", line 53, in model.forward_test() File "/mnt/oss/luci-hangzhou/junxuan/notebooks/CompositionalGAN/models/objCompose_unsupervised_model.py", line 323, in forward_test self.mask_A1_T = (self.mask_A1_T<self.opt.Thresh1_torch.max(self.mask_A1_T).data[0]).type(torch.cuda.FloatTensor) IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

Do you still have this dataset of City_car? The link provided by the author can no longer be worked。
